### PR TITLE
[security] password in command-line-argument -- is daungerious

### PR DESCRIPTION
**Pull request by mutantmonkey**
using password in command-line-argument -- is daungerious

becouse directory `/proc/<pid>/` -- has read-access-permissions from other computer-users

as solution instead of "--pass"-command-line-argument -- may be using:
1. environ variables (for example: sys.environ['POCLBM_PASS'])
2. configure files

thanks in advance!

### CODE REVIEW

**Comment by vpm** [comment]
if you use deepbit pool don't use default login and password for mining - create new miner. In others pool too.

**Comment by mikegogulski** [comment]
IMHO this is a very low-priority issue, and I say this from an infosec background. If you've got other people on the system that's performing financial transactions for you, you've already lost. Taking the password off the commandline is largely irrelevant. Besides, who in their right mind runs a multi-user system as a mining rig?

**Comment by polymorphm** [comment]
i may have some user-accounts in my OS -- for execution any unsafe proccesses (with limited permissions) . it is -- isolated secure mechanism . becouse it is not Windows-95 :-)

but if any (quasi safe) programm using "passwords in command line" -- then our OS transform to Windows-95 :-)

**Comment by mutantmonkey** [comment]
I try to execute untrusted processes with limited permissions as well, and a program running with a password on the command line severely undermines this by allowing any of these processes to read my password.

m0mchil: I've attached a commit that adds support for a JSON config file. Could you review it and merge it if it meets your standards when you get a chance? Thanks!

**Comment by m0mchil** [comment]
the password in question is not really important - it is used for submitting shares, some pools even completely ignore this... It has meaning when used for solo mining. In that case your are a) using it locally or b) using secured RPC

**Pull request closed without merging**
